name: CI for release tags

on:
  push:
    tags:
      - "v*"

jobs:
  once:
    name: Create single release for all builds
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
  build:
    name: Create cross-platform release builds, tag and upload binaries
    needs: once
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --verbose --package vouch

      - name: Zip the asset into a zip file
        id: zip_asset
        run: |
          7z a -tzip ${{ github.workspace }}/vouch-${{ matrix.os }}-${{ github.ref }}.zip ${{ github.workspace }}/target/release/vouch ${{ github.workspace }}/LICENSE

      - name: Upload release assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.once.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/vouch-${{ matrix.os }}-${{ github.ref }}.zip
          asset_name: vouch-${{ matrix.os }}-${{ github.ref }}.zip
          asset_content_type: application/octet-stream
